= Transformation

See https://doc.akka.io/docs/akka/current/cluster-usage.html?_ga=2.55825195.1211086140.1562940341-1490763741.1562697751#a-simple-cluster-example[A Simple Cluster Example]

A example that illustrates how workers, here named *backend*,
can detect and register to new master nodes, here named *frontend*.

The example application provides a service to transform text. When some text is sent to one of the frontend services, it will be delegated to one of the backend workers, which performs the transformation job, and sends the result back to the original client. New backend nodes, as well as new frontend nodes, can be added or removed to the cluster dynamically.

The backend worker that performs the transformation job is defined in
link:src/main/scala/com/stulsoft/akka/actor/cluster/TransformeationBackend.scala[TransformationBackend.scala].

Note that the *TransformationBackend* actor subscribes to cluster events to detect new, potential, frontend nodes, and send them a registration message so that they know that they can use the backend worker.

The frontend that receives user jobs and delegates to one of the registered backend workers is defined in
link:src/main/scala/com/stulsoft/akka/actor/cluster/TransformeationBackend.scala[TransformationFrontend.scala].

Note that the *TransformationFrontend* actor watch the registered backend to be able to remove it from its list of available backend workers. Death watch uses the cluster failure detector for nodes in the cluster, i.e. it detects network failures and JVM crashes, in addition to graceful termination of watched actor.

== Running

=== In one process

Run command:

 sbt "runMain com.stulsoft.akka.actor.cluster.TransformationApp"

_TransformationApp_ starts 5 actor systems (cluster members) in the same JVM process.

=== In many processes
It can be more interesting to run them in separate processes. Stop the application and run the following commands in separate terminal windows.

Run command in different terminals:

 sbt "runMain com.stulsoft.akka.actor.cluster.TransformationFrontend 2551"
 sbt "runMain com.stulsoft.akka.actor.cluster.TransformationBackend 2552"
 sbt "runMain com.stulsoft.akka.actor.cluster.TransformationBackend 0"
 sbt "runMain com.stulsoft.akka.actor.cluster.TransformationBackend 0"
 sbt "runMain com.stulsoft.akka.actor.cluster.TransformationFrontend 0"
